# Generated by Django 4.2.7 on 2025-11-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_id', models.CharField(max_length=100)),
                ('booking_date', models.DateField()),
                ('booking_time', models.CharField(blank=True, max_length=20)),
                ('client_name', models.CharField(max_length=255)),
                ('client_phone', models.CharField(max_length=50)),
                ('designer_name', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
