# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_id', models.CharField(max_length=100)),
                ('holiday_date', models.DateField()),
                ('description', models.CharField(blank=True, help_text="Optional description (e.g., 'Jour férié', 'Fermeture exceptionnelle')", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['holiday_date'],
                'unique_together': {('calendar_id', 'holiday_date')},
            },
        ),
    ]

