# Generated by Django 5.2.8 on 2025-12-05 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_authtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthToken',
        ),
    ]
