# Generated by Django 5.2.3 on 2025-12-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_authtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('concepteur', 'Concepteur'), ('technicien', 'Technicien')], default='concepteur', max_length=20),
        ),
    ]
